spring:
  application:
    name: ASE-Exagrad-Student-Service
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:file:./data/mydb
    driverClassName: org.h2.Driver
    username: sa
    password: password
server:
  error:
    include-message: always
minio:
  endpoint: http://minio-server:9000
  access-key: my-access-key
  secret-key: my-secret-key
  bucket: documents # maybe rename bucket more specific
  # add another bucket for PUB
  # TODO: get configs from file service team
