spring:
  application:
    name: ASE-Exagrad-Student-Service
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:./data/mydb
    driverClassName: org.h2.Driver
    username: sa
    password: password
server:
  error:
    include-message: always
  servlet:
    context-path: /api/v1/exagrad/student
management:
  endpoints:
    web:
      exposure:
        include: health,info,readiness,liveness
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    readiness:
      enabled: true
    liveness:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
minio-connection:
  endpoint: http://localhost:9000
  access-key: my-access-key
  secret-key: my-secret-key
  region: us-east-1

app:
  timezone: Europe/Berlin
  cors:
    allowed-origins: http://localhost:5173,http://localhost:3000
  storage:
    bucket-name: ase-team-13
  file:
    max-size: 10485760 # 10MB
    allowed-types: application/pdf,application/octet-stream,image/jpeg,image/png,image/gif,text/plain,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document
  external-apis:
    lecturer-feedback:
      base-url: https://sau-portal.de/exa-grad/grading-service/api/v1/external/feedback/student
    student:
      base-url: https://sau-portal.de/api/masterdata/studies/student/
    