apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ase-exagrad-student-service
  labels:
    app: exagrad-student-service
spec:
  ingressClassName: traefik
  rules:
    - host: sau-portal.de
      http:
        paths:
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: exagrad-student-service
                port:
                  number: 8080
