name: Deploy

on:
  push:
    branches: ["**"]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build and push image
        uses: Agile-Software-Engineering-25/build-and-publish-image@v1
        with:
          # optional — defaults shown:
          # image_name: ""                 # defaults to repo name (lowercased)
          # context: "."
          # file: "Dockerfile"
          # name_suffix: ""                # e.g. "-frontend" or "-backend"
          # platforms: "linux/amd64,linux/arm64"
          # extra_tags: ""                 # e.g. "type=raw,value=prod"
          # build_args: |                  # newline separated KEY=VALUE
          #   BASE_PATH=/team/app/my-app/
          push: true
      
      - name: Deploy to k8s
        uses: Agile-Software-Engineering-25/deploy-to-k8s@main
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          namespace: ${{ var.K8S_NAMESPACE}}