name: deploy-to-k8s

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Build and Publish Image
        uses: Agile-Software-Engineering-25/build-and-publish-image@v1
        with:
          push: true
          extra_tags: latest,${{ github.sha }}

      - name: Deploy to Namespace
        uses: Agile-Software-Engineering-25/deploy-to-k8s@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          namespace: ${{ vars.K8S_NAMESPACE }}
          image: ghcr.io/agile-software-engineering-25/team-13-backend-exagrad-student-service
          tag: latest
